TODO look if invalid data correlates and can be adjusted for in that way. 

Was it a capture thing that they mixed up 2 columns, look at the rows I am removing

TODO add gitignore

Using preprocess set 0 and data_split_0

In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer


from student_preprocess import StudentPreprocessSet0
from prof_preprocess import ProfPreprocessSet0

In [2]:
org_student_data =pd.read_csv('../../data/data_split_0/student_train_data.csv')

In [3]:
cols_to_drop=['id','Name']

imputer = SimpleImputer(missing_values=np.nan,strategy='median')


student_preprocessor = StudentPreprocessSet0(df=org_student_data,
                                             cols_to_drop=cols_to_drop,
                                             imputer=imputer,
                                             cat_encoding_type="frequency")

In [4]:
student_preprocessor.preprocess()

In [5]:
student_clean_df=student_preprocessor.df

In [6]:
student_clean_df[student_clean_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [id, Name, Gender, Age, City, Academic Pressure, Study Satisfaction, Sleep Duration, Dietary Habits, Degree, Have you ever had suicidal thoughts ?, Work/Study Hours, Financial Stress, Family History of Mental Illness, Depression]
Index: []

In [7]:
student_clean_df

,id,Name,Gender,Age,City,Academic Pressure,Study Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,0.004447,0.557205,33.0,0.034754,5.0,2.0,0.221828,0.274335,0.029015,0.632738,3.0,1.0,0.51596,1
1,8,0.008751,0.442795,24.0,0.027509,2.0,5.0,0.221828,0.355677,0.031813,0.367262,3.0,2.0,0.48404,0
2,26,0.007030,0.557205,31.0,0.049100,3.0,5.0,0.297970,0.274335,0.021519,0.367262,9.0,1.0,0.48404,0
3,30,0.009397,0.442795,28.0,0.024568,3.0,2.0,0.263324,0.355677,0.051323,0.632738,4.0,5.0,0.48404,1
4,32,0.010473,0.442795,25.0,0.037121,4.0,3.0,0.221828,0.355677,0.036619,0.632738,1.0,1.0,0.51596,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27896,140685,0.015279,0.442795,27.0,0.038663,5.0,5.0,0.221828,0.369988,0.218062,0.632738,7.0,1.0,0.48404,0
27897,140686,0.014920,0.557205,27.0,0.039811,2.0,3.0,0.297970,0.274335,0.042680,0.367262,0.0,3.0,0.48404,0
27898,140689,0.015817,0.557205,31.0,0.016534,3.0,4.0,0.221828,0.369988,0.020515,0.367262,12.0,2.0,0.51596,0
27899,140690,0.011620,0.442795,18.0,0.039811,5.0,2.0,0.297970,0.274335,0.218062,0.632738,10.0,5.0,0.51596,1
27900,140699,0.004447,0.557205,27.0,0.036116,4.0,1.0,0.297970,0.274335,0.051323,0.632738,2.0,3.0,0.48404,1

In [8]:
student_clean_df.to_csv('../../data/clean_data_0/student_train_data.csv',index=False)

In [9]:
org_prof_data =pd.read_csv('../../data/data_split_0/prof_train_data.csv')

In [10]:
cols_to_drop=['id','Name']

imputer = SimpleImputer(missing_values=np.nan,strategy='median')

prof_preprocessor = ProfPreprocessSet0(df=org_prof_data,
                                             cols_to_drop=cols_to_drop,
                                             imputer=imputer,
                                             cat_encoding_type="frequency")

In [11]:
prof_preprocessor.preprocess()

In [12]:
prof_clean_df=prof_preprocessor.df

In [13]:
prof_clean_df[prof_clean_df.isnull().any(axis=1)]

Empty DataFrame
Columns: [id, Name, Gender, Age, City, Profession, Work Pressure, Job Satisfaction, Sleep Duration, Dietary Habits, Degree, Have you ever had suicidal thoughts ?, Work/Study Hours, Financial Stress, Family History of Mental Illness, Depression]
Index: []

In [14]:
prof_clean_df

,id,Name,Gender,Age,City,Profession,Work Pressure,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,0,0.014339,0.451068,49.0,0.036491,0.025362,5.0,2.0,0.236619,0.328879,0.029973,0.539816,1.0,2.0,0.499645,0
1,1,0.007174,0.548932,26.0,0.034753,0.298409,4.0,3.0,0.270467,0.318370,0.032589,0.460184,7.0,3.0,0.499645,1
2,3,0.005374,0.548932,22.0,0.037830,0.298409,5.0,1.0,0.270467,0.352751,0.038433,0.460184,10.0,1.0,0.500355,1
3,4,0.003467,0.451068,30.0,0.033600,0.028031,1.0,1.0,0.230234,0.318370,0.038433,0.460184,9.0,4.0,0.500355,0
4,5,0.012291,0.451068,59.0,0.041333,0.011785,2.0,5.0,0.230234,0.328879,0.037138,0.539816,7.0,5.0,0.499645,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
112794,140694,0.011058,0.451068,45.0,0.041333,0.298409,2.0,5.0,0.270467,0.352751,0.087135,0.460184,1.0,5.0,0.499645,0
112795,140695,0.010278,0.451068,18.0,0.041333,0.298409,5.0,4.0,0.230234,0.318370,0.076688,0.539816,2.0,4.0,0.500355,1
112796,140696,0.001543,0.451068,41.0,0.027960,0.069266,5.0,4.0,0.262663,0.352751,0.029024,0.460184,6.0,5.0,0.500355,0
112797,140697,0.004647,0.451068,24.0,0.040987,0.017523,3.0,1.0,0.236619,0.352751,0.058589,0.539816,4.0,4.0,0.499645,0
112798,140698,0.008664,0.451068,49.0,0.032811,0.015492,5.0,2.0,0.230234,0.352751,0.030567,0.460184,10.0,1.0,0.499645,0

In [15]:
prof_clean_df.to_csv('../../data/clean_data_0/prof_train_data.csv',index=False)